name = "Dusky Neon Potato"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/VVelox/hugo-dusky-neon-potato/master/LICENSE.md"
description = "Outrun with the power of a potato."
source_repo = "https://github.com/VVelox/hugo-dusky-neon-potato.git"
tags = ["Responsive", "Blog", "Google analytics", "Disqus", "Clean", "Tags", "Minimal", "Custom Themes", "Minimalist", "Simple", "Pink", "Green", "Starter", "Dark"]
features = ["blog"]
min_version = 0.27
[author]
    name = "Dusky Neon Potato"
    homepage = "https://github.com/VVelox/hugo-dusky-neon-potato"
